### ISSUE TITLE
gh-pages - docs

### ISSUE THREAD

**Issue by layik** [RACFoundation/webTRISr#4]
Looking at playing with web`TRIS` data and the package looks like a great effort. Downloaded and ran the tests all look good.

For someone like me or an average user, either a vignette or `gh-pages` branch and `http://departmentfortransport.github.io/webtrisr` URL would be much better than the CRAN pdf guide. Like the sf or our stats19 package: https://r-spatial.github.io/sf/

Wonder if that could be done so I can possibly contribute a little if we ever use the package. 

Thanks

ps: one easy contribution I could do, is turn the sites into an `sf` object if a switch is flicked as parameter. Obviously that means another dependency for the package.

``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
library(webTRISr)
sites = webTRISr::webtris_sites()
sites_sf = st_as_sf(sites, coords = grep(pattern = "Long|Lat", names(sites)), 
                    crs = 4326)
names(sites_sf)
#> [1] "Id"          "Name"        "Description" "Status"      "geometry"
```

<sup>Created on 2019-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
![image](https://user-images.githubusercontent.com/408568/58175072-3b66a780-7c97-11e9-87a2-abca10d1edfe.png)

**Comment by willbowditch** [comment]
Hi @layik - thanks for the PR https://github.com/departmentfortransport/webTRISr/pull/5, looks like a good addition! Since developing this I've left the Department for Transport. So this project is no longer actively maintained and I'm unable to merge it due to permissions. Would you be interested in maintaining the package going forward? If not, I'll see if we can get the repository marked as inactive on GitHub.

**Comment by wengraf** [comment]
If there is anything the RAC Foundation can do in helping this staying active, please ask.

**Comment by layik** [comment]
Hi @willbowditch. Hi @wengraf. It probably is better if RAC could "officially" own it, as I would not be doing a better job than DfT to be honest.

But happy to contribute if we keep on using it.

**Comment by willbowditch** [comment]
Thanks both. @wengraf would you, or anyone at the RAC, be happy to take on the maintenance of this?

**Comment by wengraf** [comment]
@willbowditch : In all likelihood, yes, but I'm just going to double-check...

**Comment by wengraf** [comment]
@willbowditch : Hi Will, I'm still in the process of double-checking.... I'll post again when we get a reply to our email....

**Comment by willbowditch** [comment]
Thanks @wengraf - if its not possible, I can just move it to my personal GitHub account and maintain it from there. I doubt I'll be adding any features, but happy to merge PRs etc.

**Comment by layik** [comment]
IF we are going private accounts, perhaps I might get push/collaborator rights on it @willbowditch. I might get graduate/undergraduates to use/contribute to it. My original thoughts still the same, RAC much better. Going to close the thread and hopefully @wengraf will be able to finalise things :)

**Comment by wengraf** [comment]
OK, @willbowditch and @layik, this is the RACF's now....

**Comment by layik** [comment]
Great job. Keeping it alive.

**Comment by willbowditch** [comment]
Nice one, thanks @wengraf 

Noticed the build is now failing: https://travis-ci.org/RACFoundation/webTRISr

Likely due to dependencies missing now sf is used. 

Would probably be a good idea to setup master as requiring the travis integrations to pass before PRs can be merged to prevent this. Happy to fix and set this up if useful.

**Comment by wengraf** [comment]
Hi @willbowditch - it took a couple of goes at changing .travis.yml, but the build is now passing.

**Comment by wengraf** [comment]
Hello again, @willbowditch .  Fixed the Travis stuff, and submitted to CRAN all updated and checked.  CRAN says they will be in touch with the package's previous maintainer.  What happens if they email you at your @dft.gov.uk address?

**Comment by willbowditch** [comment]
Awesome. Good point on the CRAN email... not entirely sure what will happen there, but I suspect that address has been closed and they'll get a delivery failure. I can ping you my new email address if that'll help.

**Comment by wengraf** [comment]
@willbowditch it all worked out.  I suspect your bounced DfT email was enough to confirm my account of the switch.
